"""
enforce.py — Stage 5: Enforce

Reads assessment-results.json and poam.json, prints a pass/fail
summary, and optionally opens a GitHub issue for failures.

USAGE:
  python enforce.py --results oscal/assessment-results.json --poam oscal/poam.json
  python enforce.py --help

EXIT CODES:
  0 — all controls confirmed, no open POA&M items
  1 — findings exist
"""

import argparse
import json
import os
import sys
from datetime import datetime, timezone

sys.path.insert(0, os.path.dirname(__file__))
from pipeline_utils import load_oscal, now_iso


def count_findings(ar: dict) -> dict:
    """Count findings by status."""
    counts = {"satisfied": 0, "not-satisfied": 0}
    results = ar.get("assessment-results", {}).get("results", [])
    if not results:
        return counts

    for finding in results[0].get("findings", []):
        status = finding.get("target", {}).get("status", {}).get("state", "unknown")
        counts[status] = counts.get(status, 0) + 1

    return counts


def get_failed_findings(ar: dict) -> list:
    """Get all failed findings with details."""
    failed = []
    results = ar.get("assessment-results", {}).get("results", [])
    if not results:
        return failed

    for finding in results[0].get("findings", []):
        status = finding.get("target", {}).get("status", {}).get("state", "")
        if status == "not-satisfied":
            source = next(
                (p["value"] for p in finding.get("props", []) if p["name"] == "source"),
                "unknown"
            )
            control = finding.get("target", {}).get("target-id", "unknown")
            failed.append({
                "control": control,
                "source": source,
                "title": finding.get("title", ""),
                "description": finding.get("description", ""),
            })
    return failed


def create_github_issue(poam_items: list, failed_findings: list, repo: str = None):
    """Create a GitHub issue with the finding summary."""
    token = os.environ.get("GITHUB_TOKEN")
    if not token:
        print("    WARN: GITHUB_TOKEN not set — skipping issue creation")
        return

    if not repo:
        org = os.environ.get("GITHUB_ORG", "")
        repo = f"{org}/oscal-pipeline-workshop" if org else None
    if not repo:
        print("    WARN: Could not determine repo — skipping issue creation")
        return

    import requests

    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    title = f"[Pipeline] {len(poam_items)} findings — {today}"

    body = f"## Pipeline Assessment Results\n\n"
    body += f"**Date:** {today}\n"
    body += f"**POA&M items:** {len(poam_items)}\n"
    body += f"**Failed checks:** {len(failed_findings)}\n\n"

    body += f"### Failed Checks\n\n"
    body += f"| Control | Source | Finding |\n"
    body += f"|---------|--------|----------|\n"
    for f in failed_findings:
        body += f"| {f['control'].upper()} | {f['source']} | {f['title']} |\n"

    body += f"\n### POA&M Items\n\n"
    for item in poam_items:
        control = next((p["value"] for p in item.get("props", []) if p["name"] == "control-id"), "?")
        source = next((p["value"] for p in item.get("props", []) if p["name"] == "source"), "?")
        body += f"- **{control.upper()}** ({source}): {item['title']}\n"

    body += f"\n---\nGenerated by OSCAL Pipeline `enforce.py`\n"

    headers = {"Authorization": f"token {token}", "Accept": "application/vnd.github.v3+json"}
    resp = requests.post(
        f"https://api.github.com/repos/{repo}/issues",
        headers=headers,
        json={"title": title, "body": body, "labels": ["pipeline", "compliance"]},
    )

    if resp.status_code == 201:
        issue_url = resp.json()["html_url"]
        print(f"    GitHub issue created: {issue_url}")
    else:
        print(f"    WARN: Could not create issue: {resp.status_code} {resp.text[:200]}")


def main():
    parser = argparse.ArgumentParser(description="Stage 5: Enforce — gate and alert on findings")
    parser.add_argument("--results", default="oscal/assessment-results.json", help="Assessment results")
    parser.add_argument("--poam", default="oscal/poam.json", help="POA&M file")
    parser.add_argument("--repo", default=None, help="GitHub repo (owner/name) for issue creation")
    parser.add_argument("--no-issue", action="store_true", help="Skip GitHub issue creation")
    args = parser.parse_args()

    print(f"\n{'='*62}")
    print(f"  OSCAL Pipeline — Stage 5: ENFORCE")
    print(f"  Gate and alert on findings")
    print(f"{'='*62}")

    # Load inputs
    print(f"\n  Loading assessment results: {args.results}")
    ar = load_oscal(args.results)
    counts = count_findings(ar)
    failed = get_failed_findings(ar)

    print(f"  Loading POA&M: {args.poam}")
    poam = load_oscal(args.poam)
    poam_items = poam.get("plan-of-action-and-milestones", {}).get("poam-items", [])

    # Determine pass/fail
    has_findings = len(poam_items) > 0

    print(f"\n{'='*62}")
    if has_findings:
        print(f"  RESULT: FAIL")
    else:
        print(f"  RESULT: PASS")
    print(f"{'='*62}")
    print(f"  Checks passed:     {counts.get('satisfied', 0)}")
    print(f"  Checks failed:     {counts.get('not-satisfied', 0)}")
    print(f"  POA&M items:       {len(poam_items)}")

    if failed:
        print(f"{'─'*62}")
        print(f"  Failed checks:")
        for f in failed:
            print(f"    ✗ [{f['control'].upper():8s}] [{f['source']:20s}] {f['title']}")

    if poam_items:
        print(f"{'─'*62}")
        print(f"  POA&M items:")
        for item in poam_items:
            control = next((p["value"] for p in item.get("props", []) if p["name"] == "control-id"), "?")
            source = next((p["value"] for p in item.get("props", []) if p["name"] == "source"), "?")
            print(f"    ✗ [{control.upper():8s}] [{source:20s}] {item['title']}")

    print(f"{'='*62}\n")

    # Create GitHub issue if failures exist
    if has_findings and not args.no_issue:
        print(f"  Creating GitHub issue...")
        create_github_issue(poam_items, failed, args.repo)

    sys.exit(1 if has_findings else 0)


if __name__ == "__main__":
    main()
