"""
export_to_linear.py — Push POA&M items to Linear as issues via GraphQL API.

Reads oscal/poam.json and creates a Linear issue for each POA&M item.
"""

import sys, os, json, argparse
from datetime import datetime, timezone

import requests

sys.path.insert(0, os.path.dirname(__file__))
from pipeline_utils import load_oscal

# ── Banner ───────────────────────────────────────────────────────────────────
BANNER = """
==============================================================
  OSCAL Pipeline — Export POA&M to Linear
==============================================================
"""

# ── Linear GraphQL endpoint ──────────────────────────────────────────────────
LINEAR_API_URL = "https://api.linear.app/graphql"

# ── Priority mapping (control family → Linear priority) ──────────────────────
# 1 = Urgent, 2 = High, 3 = Medium, 4 = Low, 0 = No priority
PRIORITY_MAP = {
    "sc": 1, "ia": 1,                      # Urgent — security/identity
    "ac": 2, "au": 2, "cm": 2, "si": 2,    # High
    "ra": 3, "sa": 3, "at": 3, "ir": 3,    # Medium
}

# ── Recommended action mapping ───────────────────────────────────────────────
ACTION_MAP = {
    "ia-2":  "Enable MFA for all IAM users",
    "sc-28": "Enable server-side encryption on all storage resources",
    "sc-7":  "Restrict public access and enforce network boundaries",
    "sc-8":  "Enforce TLS/HTTPS on all data in transit",
    "sc-12": "Enable automatic key rotation on all KMS keys",
    "cm-3":  "Enable branch protection with required reviews",
    "au-2":  "Enable VPC flow logs and comprehensive audit logging",
    "au-9":  "Enable CloudTrail log file validation",
    "ac-2":  "Review and disable unused or stale accounts",
    "ac-6":  "Remove wildcard IAM policies, enforce least privilege",
    "sa-11": "Remediate open code scanning alerts",
    "si-2":  "Patch known vulnerabilities in dependencies",
    "si-4":  "Enable GuardDuty and Security Hub for monitoring",
    "ra-5":  "Enable Dependabot and remediate open vulnerability alerts",
}


# ── Helpers ──────────────────────────────────────────────────────────────────

def get_prop(props: list, name: str) -> str:
    """Return the value of the first prop matching *name*, or ''."""
    for p in props:
        if p.get("name") == name:
            return p.get("value", "")
    return ""


def linear_request(api_key: str, query: str, variables: dict = None) -> dict:
    """Send a GraphQL request to Linear and return the JSON response."""
    headers = {
        "Content-Type": "application/json",
        "Authorization": api_key,
    }
    payload = {"query": query}
    if variables:
        payload["variables"] = variables

    resp = requests.post(LINEAR_API_URL, headers=headers, json=payload, timeout=30)
    resp.raise_for_status()
    return resp.json()


def get_team_id(api_key: str, team_key: str) -> str | None:
    """Look up a Linear team ID by its key (e.g. 'GRC')."""
    query = "query { teams { nodes { id name key } } }"
    data = linear_request(api_key, query)
    teams = data.get("data", {}).get("teams", {}).get("nodes", [])
    for team in teams:
        if team.get("key", "").upper() == team_key.upper():
            return team["id"]
    return None


def get_priority(control_id: str) -> int:
    """Map a control ID to a Linear priority number."""
    family = control_id.lower().split("-")[0] if "-" in control_id else control_id.lower()
    return PRIORITY_MAP.get(family, 3)  # Default: Medium


def recommended_action(control_id: str) -> str:
    """Return recommended action for a control, or a generic fallback."""
    return ACTION_MAP.get(control_id.lower(), "Review and remediate")


def build_description(item: dict, control_id: str, source: str,
                      screenshot_url: str = None) -> str:
    """Build a Markdown description for the Linear issue."""
    desc = item.get("description", "")
    action = recommended_action(control_id)

    body = (
        f"## Finding\n\n"
        f"{desc}\n\n"
        f"**Control:** {control_id.upper()}\n"
        f"**Source:** {source}\n"
        f"**Status:** Open\n\n"
    )

    if screenshot_url:
        body += (
            f"## Evidence\n\n"
            f"![{control_id.upper()} evidence]({screenshot_url})\n\n"
        )

    body += (
        f"## Recommended Action\n\n"
        f"{action}\n\n"
        f"---\n"
        f"*Generated by OSCAL Pipeline*"
    )
    return body


def upload_file(api_key: str, file_path: str, filename: str) -> str | None:
    """Upload a file to Linear and return its asset URL."""
    if not os.path.exists(file_path):
        return None

    size = os.path.getsize(file_path)
    mutation = """
    mutation FileUpload($size: Int!, $contentType: String!, $filename: String!) {
      fileUpload(size: $size, contentType: $contentType, filename: $filename) {
        uploadFile {
          uploadUrl
          assetUrl
          headers { key value }
        }
        success
      }
    }
    """
    data = linear_request(api_key, mutation, {
        "size": size, "contentType": "image/png", "filename": filename,
    })
    upload = data.get("data", {}).get("fileUpload", {})
    if not upload.get("success"):
        return None

    upload_file_data = upload["uploadFile"]
    headers = {h["key"]: h["value"] for h in upload_file_data.get("headers", [])}
    headers["Content-Type"] = "image/png"

    with open(file_path, "rb") as f:
        resp = requests.put(upload_file_data["uploadUrl"], headers=headers, data=f.read(), timeout=30)

    if resp.status_code in (200, 201):
        return upload_file_data["assetUrl"]
    return None


def build_screenshot_map(ar_path: str) -> dict:
    """
    Build a map of (control_id, source) → screenshot_path from assessment results.
    Walks findings → related-observations → evidence-screenshot prop.
    """
    if not os.path.exists(ar_path):
        return {}

    ar = load_oscal(ar_path)
    results = ar.get("assessment-results", {}).get("results", [])
    if not results:
        return {}

    # Index observations by UUID
    obs_index = {}
    for obs in results[0].get("observations", []):
        obs_index[obs["uuid"]] = obs

    screenshot_map = {}
    for finding in results[0].get("findings", []):
        control = finding.get("target", {}).get("target-id", "")
        source = next(
            (p["value"] for p in finding.get("props", []) if p["name"] == "source"), ""
        )
        for ref in finding.get("related-observations", []):
            obs = obs_index.get(ref.get("observation-uuid", ""))
            if not obs:
                continue
            for p in obs.get("props", []):
                if p["name"] == "evidence-screenshot":
                    key = (control.lower(), source.lower())
                    screenshot_map[key] = p["value"]
                    break

    return screenshot_map


def create_issue(api_key: str, team_id: str, title: str, description: str, priority: int) -> dict | None:
    """Create a Linear issue and return the issue data, or None on failure."""
    mutation = """
    mutation IssueCreate($input: IssueCreateInput!) {
      issueCreate(input: $input) {
        success
        issue {
          id
          identifier
          url
        }
      }
    }
    """
    variables = {
        "input": {
            "teamId": team_id,
            "title": title,
            "description": description,
            "priority": priority,
        }
    }
    data = linear_request(api_key, mutation, variables)
    result = data.get("data", {}).get("issueCreate", {})
    if result.get("success"):
        return result.get("issue")
    return None


# ── Main ─────────────────────────────────────────────────────────────────────

def export_to_linear(poam_path: str, team_key: str, api_key: str,
                     ar_path: str = None):
    print(BANNER)

    # Load POA&M
    data = load_oscal(poam_path)
    items = data.get("plan-of-action-and-milestones", {}).get("poam-items", [])
    print(f"  POA&M items found : {len(items)}")
    print(f"  Linear team key   : {team_key}")

    # Load screenshot map from assessment results
    screenshot_map = {}
    if ar_path:
        print(f"  Loading screenshots from: {ar_path}")
        screenshot_map = build_screenshot_map(ar_path)
        print(f"  Screenshots mapped: {len(screenshot_map)}")
    print()

    # Resolve team ID
    print("  Resolving team ID...")
    team_id = get_team_id(api_key, team_key)
    if not team_id:
        print(f"  ERROR: Team with key '{team_key}' not found in Linear.")
        sys.exit(1)
    print(f"  Team ID           : {team_id}")
    print()

    # Upload cache — avoid uploading the same screenshot multiple times
    upload_cache = {}

    # Create issues
    created = 0
    for item in items:
        props = item.get("props", [])
        control_id = get_prop(props, "control-id")
        source = get_prop(props, "source")

        # Look up and upload screenshot
        screenshot_url = None
        ss_key = (control_id.lower(), source.lower())
        ss_path = screenshot_map.get(ss_key)
        if ss_path:
            if ss_path in upload_cache:
                screenshot_url = upload_cache[ss_path]
            else:
                filename = os.path.basename(ss_path)
                screenshot_url = upload_file(api_key, ss_path, filename)
                if screenshot_url:
                    upload_cache[ss_path] = screenshot_url

        title = f"[POA&M] {control_id.upper()}: {item.get('title', '')}"
        description = build_description(item, control_id, source, screenshot_url)
        priority = get_priority(control_id)

        try:
            issue = create_issue(api_key, team_id, title, description, priority)
            if issue:
                ss_indicator = " 📎" if screenshot_url else ""
                print(f"  Created: {issue['identifier']}  {issue['url']}{ss_indicator}")
                created += 1
            else:
                print(f"  FAILED:  {title}")
        except Exception as e:
            print(f"  ERROR:   {title} — {e}")

    print()
    print(f"  Summary: {created} issues created ({len(upload_cache)} screenshots uploaded)")
    print()


def main():
    parser = argparse.ArgumentParser(description="Export POA&M items to Linear")
    parser.add_argument("--poam", default="oscal/poam.json")
    parser.add_argument("--results", default="oscal/assessment-results.json",
                        help="Assessment results JSON (for screenshot evidence)")
    parser.add_argument("--team", default=os.environ.get("LINEAR_TEAM_KEY", "GRC"))
    args = parser.parse_args()

    api_key = os.environ.get("LINEAR_API_KEY")
    if not api_key:
        print("  LINEAR_API_KEY not set — skipping Linear export.")
        sys.exit(0)

    if not os.path.exists(args.poam):
        print(f"  ERROR: POA&M file not found: {args.poam}")
        print("         Run the pipeline first to generate oscal/poam.json")
        sys.exit(1)

    ar_path = args.results if os.path.exists(args.results) else None
    export_to_linear(args.poam, args.team, api_key, ar_path)


if __name__ == "__main__":
    main()
