"""
export_to_linear.py — Push POA&M items to Linear as issues via GraphQL API.

Reads oscal/poam.json and creates a Linear issue for each POA&M item.
"""

import sys, os, json, argparse
from datetime import datetime, timezone

import requests

sys.path.insert(0, os.path.dirname(__file__))
from pipeline_utils import load_oscal

# ── Banner ───────────────────────────────────────────────────────────────────
BANNER = """
==============================================================
  OSCAL Pipeline — Export POA&M to Linear
==============================================================
"""

# ── Linear GraphQL endpoint ──────────────────────────────────────────────────
LINEAR_API_URL = "https://api.linear.app/graphql"

# ── Priority mapping (control family → Linear priority) ──────────────────────
# 1 = Urgent, 2 = High, 3 = Medium, 4 = Low, 0 = No priority
PRIORITY_MAP = {
    "sc": 1, "ia": 1,                      # Urgent — security/identity
    "ac": 2, "au": 2, "cm": 2, "si": 2,    # High
    "ra": 3, "sa": 3, "at": 3, "ir": 3,    # Medium
}

# ── Recommended action mapping ───────────────────────────────────────────────
ACTION_MAP = {
    "ia-2":  "Enable MFA for all IAM users",
    "sc-28": "Enable server-side encryption on all storage resources",
    "sc-7":  "Restrict public access and enforce network boundaries",
    "sc-8":  "Enforce TLS/HTTPS on all data in transit",
    "sc-12": "Enable automatic key rotation on all KMS keys",
    "cm-3":  "Enable branch protection with required reviews",
    "au-2":  "Enable VPC flow logs and comprehensive audit logging",
    "au-9":  "Enable CloudTrail log file validation",
    "ac-2":  "Review and disable unused or stale accounts",
    "ac-6":  "Remove wildcard IAM policies, enforce least privilege",
    "sa-11": "Remediate open code scanning alerts",
    "si-2":  "Patch known vulnerabilities in dependencies",
    "si-4":  "Enable GuardDuty and Security Hub for monitoring",
    "ra-5":  "Enable Dependabot and remediate open vulnerability alerts",
}


# ── Helpers ──────────────────────────────────────────────────────────────────

def get_prop(props: list, name: str) -> str:
    """Return the value of the first prop matching *name*, or ''."""
    for p in props:
        if p.get("name") == name:
            return p.get("value", "")
    return ""


def linear_request(api_key: str, query: str, variables: dict = None) -> dict:
    """Send a GraphQL request to Linear and return the JSON response."""
    headers = {
        "Content-Type": "application/json",
        "Authorization": api_key,
    }
    payload = {"query": query}
    if variables:
        payload["variables"] = variables

    resp = requests.post(LINEAR_API_URL, headers=headers, json=payload, timeout=30)
    resp.raise_for_status()
    return resp.json()


def get_team_id(api_key: str, team_key: str) -> str | None:
    """Look up a Linear team ID by its key (e.g. 'GRC')."""
    query = "query { teams { nodes { id name key } } }"
    data = linear_request(api_key, query)
    teams = data.get("data", {}).get("teams", {}).get("nodes", [])
    for team in teams:
        if team.get("key", "").upper() == team_key.upper():
            return team["id"]
    return None


def get_priority(control_id: str) -> int:
    """Map a control ID to a Linear priority number."""
    family = control_id.lower().split("-")[0] if "-" in control_id else control_id.lower()
    return PRIORITY_MAP.get(family, 3)  # Default: Medium


def recommended_action(control_id: str) -> str:
    """Return recommended action for a control, or a generic fallback."""
    return ACTION_MAP.get(control_id.lower(), "Review and remediate")


def build_description(item: dict, control_id: str, source: str) -> str:
    """Build a Markdown description for the Linear issue."""
    desc = item.get("description", "")
    action = recommended_action(control_id)

    return (
        f"## Finding\n\n"
        f"{desc}\n\n"
        f"**Control:** {control_id.upper()}\n"
        f"**Source:** {source}\n"
        f"**Status:** Open\n\n"
        f"## Recommended Action\n\n"
        f"{action}\n\n"
        f"---\n"
        f"*Generated by OSCAL Pipeline*"
    )


def create_issue(api_key: str, team_id: str, title: str, description: str, priority: int) -> dict | None:
    """Create a Linear issue and return the issue data, or None on failure."""
    mutation = """
    mutation IssueCreate($input: IssueCreateInput!) {
      issueCreate(input: $input) {
        success
        issue {
          id
          identifier
          url
        }
      }
    }
    """
    variables = {
        "input": {
            "teamId": team_id,
            "title": title,
            "description": description,
            "priority": priority,
        }
    }
    data = linear_request(api_key, mutation, variables)
    result = data.get("data", {}).get("issueCreate", {})
    if result.get("success"):
        return result.get("issue")
    return None


# ── Main ─────────────────────────────────────────────────────────────────────

def export_to_linear(poam_path: str, team_key: str, api_key: str):
    print(BANNER)

    # Load POA&M
    data = load_oscal(poam_path)
    items = data.get("plan-of-action-and-milestones", {}).get("poam-items", [])
    print(f"  POA&M items found : {len(items)}")
    print(f"  Linear team key   : {team_key}")
    print()

    # Resolve team ID
    print("  Resolving team ID...")
    team_id = get_team_id(api_key, team_key)
    if not team_id:
        print(f"  ERROR: Team with key '{team_key}' not found in Linear.")
        sys.exit(1)
    print(f"  Team ID           : {team_id}")
    print()

    # Create issues
    created = 0
    for item in items:
        props = item.get("props", [])
        control_id = get_prop(props, "control-id")
        source = get_prop(props, "source")

        title = f"[POA&M] {control_id.upper()}: {item.get('title', '')}"
        description = build_description(item, control_id, source)
        priority = get_priority(control_id)

        try:
            issue = create_issue(api_key, team_id, title, description, priority)
            if issue:
                print(f"  Created: {issue['identifier']}  {issue['url']}")
                created += 1
            else:
                print(f"  FAILED:  {title}")
        except Exception as e:
            print(f"  ERROR:   {title} — {e}")

    print()
    print(f"  Summary: {created} issues created")
    print()


def main():
    parser = argparse.ArgumentParser(description="Export POA&M items to Linear")
    parser.add_argument("--poam", default="oscal/poam.json")
    parser.add_argument("--team", default=os.environ.get("LINEAR_TEAM_KEY", "GRC"))
    args = parser.parse_args()

    api_key = os.environ.get("LINEAR_API_KEY")
    if not api_key:
        print("  LINEAR_API_KEY not set — skipping Linear export.")
        sys.exit(0)

    if not os.path.exists(args.poam):
        print(f"  ERROR: POA&M file not found: {args.poam}")
        print("         Run the pipeline first to generate oscal/poam.json")
        sys.exit(1)

    export_to_linear(args.poam, args.team, api_key)


if __name__ == "__main__":
    main()
